/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Atmosphere: typeof import('./src/components/background/Atmosphere.vue')['default']
    FaqSection: typeof import('./src/components/sections/FaqSection.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    LegalModal: typeof import('./src/components/modal/LegalModal.vue')['default']
    MatchesSection: typeof import('./src/components/sections/MatchesSection.vue')['default']
    PartnersSection: typeof import('./src/components/sections/PartnersSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeading: typeof import('./src/components/widgets/SectionHeading.vue')['default']
    SiteFooter: typeof import('./src/components/layout/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/layout/SiteHeader.vue')['default']
    StaffSection: typeof import('./src/components/sections/StaffSection.vue')['default']
    TeamSection: typeof import('./src/components/sections/TeamSection.vue')['default']
    Tooltip: typeof import('./src/components/widgets/Tooltip.vue')['default']
  }
}
